{
 "title": "Loki Syslog AIO - Overview",
 "tags": [ "syslog" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({job=\"syslog\"}, host)"
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": "info,debug,warn,error,ERR,DNS,auth_failures,wpa_auth_failures,-"
   },
   { "name": "free_form_filter", "label": "Free Form Filter" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Log Line Counts By Host (Unfiltered)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Counts By Host ($host) - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=~\"$host\", job=\"syslog\"} [$__interval] |~ \"$free_form_filter\" |~ \"$filter\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logs By Host - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=~\"$host\"} |~ \"$free_form_filter\" |~ \"$filter\""
    }
   ]
  }
 ]
}