networks:
  loki: {}
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      loki: null
    ports:
    - published: 8080
      target: 8080
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
  grafana:
    image: grafana/grafana-oss:10.2.3
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/no_folder/loki_syslog_aio_overview.json
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: always
    volumes:
    - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    depends_on:
    - minio
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: always
    volumes:
    - ./config/loki-config-s3.yml:/etc/loki/loki-config.yml:ro
  minio:
    image: minio/minio:latest
    command: -c 'mkdir -p /data/loki && /usr/bin/docker-entrypoint.sh minio server /data --console-address ":9001"'
    container_name: minio
    entrypoint: sh
    environment:
      MINIO_ACCESS_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SECRET_KEY: minio456
      # Newer versions of minio uses these env variables.
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio456
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      loki: null
    ports:
    - published: 9000
      target: 9000
    - published: 9001
      target: 9001   
    restart: always
  node-exporter:
    image: prom/node-exporter:latest
    command: --path.rootfs=/host
    container_name: node-exporter
    networks:
      loki: null
    pid: host
    ports:
    - published: 9100
      target: 9100
    restart: always
    volumes:
    - /:/host:ro,rslave
  prometheus:
    image: prom/prometheus:latest
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-admin-api
    - --web.enable-lifecycle
    container_name: prometheus
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      loki: null
    ports:
    - published: 9090
      target: 9090
    restart: always
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  promtail:
    image: grafana/promtail:2.8.7
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: always
    volumes:
    - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
  syslog-ng:
    image: pcanham/syslog-ng:0.1.1
    build:
      context: ./syslog-ng
      args:
          GEOIP_ACCOUNTID: GEOIP_ACCOUNTID_VALUE
          GEOIP_LICENSE: GEOIP_LICENSE_VALUE      
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      TZ: "Europe/London"
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    networks:
      loki: null
    ports:
    - protocol: udp
      published: 513
      target: 513
    - protocol: tcp
      published: 513
      target: 513
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: always
    volumes:
    - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
    - /etc/localtime:/etc/localtime:ro
version: '3.3'
